substitutions:
  device_name: hag
  friendly_name: Home Assistant Gauge
  
  power_pulse_pin: GPIO19
  power_pulse_rate: '2000' # imp/kWh

  gas_pulse_pin: GPIO22
  gas_passthrough_output_pin: GPIO23
  gas_passthrough_input_pin: GPIO21
  gas_pulse_rate: '100' # imp/m³

  led_yellow_pin: GPIO26
  led_blue_pin: GPIO25
  led_delay: 0.1s
  
esphome:
  name: '${device_name}'
  platform: ESP32
  board: nodemcu-32s
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

ota:
  password: !secret password

api:

output:
  - platform: gpio
    pin: ${led_yellow_pin}
    id: output_yellow
  - platform: gpio
    pin: ${led_blue_pin}
    id: output_blue
  - platform: gpio
    id: gas_passthrough_output
    pin:
      number: ${gas_passthrough_output_pin}
    
light:
  - platform: binary
    internal: true
    id: led_yellow
    name: Yellow
    output: output_yellow
  - platform: binary
    internal: true
    id: led_blue
    name: Blue
    output: output_blue
    
binary_sensor:
  - platform: gpio
    name: "${friendly_name} - Gas Pulse Input"
    internal: true
    pin:
      number: ${gas_pulse_pin}
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 500ms
      - delayed_off: 500ms
    on_press:
      then:
        - output.turn_on: gas_passthrough_output
        - delay: 10ms
        - output.turn_off: gas_passthrough_output
      
text_sensor:
  - platform: version
    hide_timestamp: true
    name: "${friendly_name} - ESPHome Version"

sensor:
  - platform: pulse_meter
    name: '${friendly_name} - Power Consumption'
    id: sensor_energy_pulse_meter
    pin: ${power_pulse_pin}
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    unit_of_measurement: 'W'
    accuracy_decimals: 0
    on_value:
      then:
        - light.turn_on:
            id: led_yellow
        - delay: ${led_delay}
        - light.turn_off:
            id: led_yellow
    filters:
      - lambda: return x * ((60.0 / ${power_pulse_rate}) * 1000.0);
    total:
      name: '${friendly_name} - Total Energy'
      id: sensor_total_energy
      state_class: total_increasing
      device_class: energy
      icon: mdi:flash-outline
      unit_of_measurement: 'kWh'
      accuracy_decimals: 3
      filters:
        - lambda: return x * (1.0 / ${power_pulse_rate});
  - platform: pulse_meter
    name: '${friendly_name} - Gas Consumption'
    id: sensor_gas_pulse_meter
    pin:
      number: ${gas_passthrough_input_pin}
      mode: INPUT_PULLUP
    internal_filter: 13us # max for ESP32
    timeout: 1min
    state_class: measurement
    device_class: gas
    unit_of_measurement: 'm³/h'
    icon: mdi:fire
    accuracy_decimals: 2
    on_value:
      then:
        - light.turn_on:
            id: led_blue
        - delay: ${led_delay}
        - light.turn_off:
            id: led_blue
    filters:
      - lambda: return x * (1.0 / ${gas_pulse_rate}) * 60;
    total:
      name: '${friendly_name} - Total Gas'
      id: sensor_total_gas
      state_class: total_increasing
      device_class: gas
      icon: mdi:fire
      unit_of_measurement: 'm³'
      accuracy_decimals: 2
      filters:
        - lambda: return x * (1.0 / ${gas_pulse_rate});

